-- Adds an exalt-type column to charm_library and backfills it from the source book data.
-- Safe to run once. Run in the Supabase SQL editor (bypasses RLS as table owner).

alter table public.charm_library add column if not exists type text not null default 'Universal';

update public.charm_library set type = 'Universal' where ability = 'Any' and name = '[Ability] Excellency';
update public.charm_library set type = 'Universal' where ability = 'Athletics (Evasion)' and name = 'Flickering Shadow Evasion';
update public.charm_library set type = 'Universal' where ability = 'Athletics (Evasion)' and name = 'Flow Like Blood';
update public.charm_library set type = 'Universal' where ability = 'Athletics (Evasion)' and name = 'Mongoose-and-Cobra Escape';
update public.charm_library set type = 'Universal' where ability = 'Athletics (Evasion)' and name = 'Reed in the Wind';
update public.charm_library set type = 'Universal' where ability = 'Athletics (Movement)' and name = 'Eagle-Wing Style';
update public.charm_library set type = 'Universal' where ability = 'Athletics (Movement)' and name = 'Graceful Crane Stance';
update public.charm_library set type = 'Universal' where ability = 'Athletics (Movement)' and name = 'Lightning Speed';
update public.charm_library set type = 'Universal' where ability = 'Athletics (Movement)' and name = 'Monkey Leap Technique';
update public.charm_library set type = 'Universal' where ability = 'Awareness' and name = 'All-Encompassing Sorcerer''s Sight';
update public.charm_library set type = 'Universal' where ability = 'Awareness' and name = 'Ambush Sensing Premonition';
update public.charm_library set type = 'Universal' where ability = 'Awareness' and name = 'Crafty Observation Method';
update public.charm_library set type = 'Universal' where ability = 'Awareness' and name = 'Enhanced Senses';
update public.charm_library set type = 'Universal' where ability = 'Awareness' and name = 'Evidence-Discerning Method';
update public.charm_library set type = 'Universal' where ability = 'Awareness' and name = 'Jade Leaves a Trail';
update public.charm_library set type = 'Universal' where ability = 'Awareness' and name = 'Sagacious Reading of Intent';
update public.charm_library set type = 'Universal' where ability = 'Awareness' and name = 'Spirit-Cutting Glance';
update public.charm_library set type = 'Universal' where ability = 'Awareness' and name = 'Witness Rapport Technique';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Attack) / Ranged Combat / Physique (Resistance)' and name = 'Arsenal-Summoning Gesture';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Attack)' and name = 'Dragon Coil Technique';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Attack)' and name = 'Excellent Strike';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Attack)' and name = 'Fists of Iron Technique';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Attack)' and name = 'Guard-Breaking Technique';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Attack)' and name = 'Heaven Thunder Hammer';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Attack)' and name = 'Many-Attacks Technique';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Attack)' and name = 'Swift Counterattack';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Defense)' and name = 'Bulwark Stance';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Defense)' and name = 'Heavenly Guardian Defense';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Defense) / Integrity' and name = 'Loyal Guardian Approach';
update public.charm_library set type = 'Universal' where ability = 'Close Combat (Defense)' and name = 'Portentous Warding Defense';
update public.charm_library set type = 'Universal' where ability = 'Craft' and name = 'Clever Improvisation Method';
update public.charm_library set type = 'Universal' where ability = 'Craft' and name = 'Durability-Enhancing Procedure';
update public.charm_library set type = 'Universal' where ability = 'Craft' and name = 'Efficient Crafting Technique';
update public.charm_library set type = 'Universal' where ability = 'Craft / Stealth' and name = 'Flawless Counterfeit Technique';
update public.charm_library set type = 'Universal' where ability = 'Craft / Embassy' and name = 'Morale-Boosting Meal';
update public.charm_library set type = 'Universal' where ability = 'Craft' and name = 'Quickening the Forge';
update public.charm_library set type = 'Universal' where ability = 'Craft' and name = 'Sudden Trap Attack';
update public.charm_library set type = 'Universal' where ability = 'Craft' and name = 'Terrain-Altering Advantage';
update public.charm_library set type = 'Universal' where ability = 'Craft / Sagacity' and name = 'Wonder-Crafting Initiation';
update public.charm_library set type = 'Universal' where ability = 'Embassy' and name = 'Bureau-Breaking Method';
update public.charm_library set type = 'Universal' where ability = 'Embassy' and name = 'Deft Official''s Way';
update public.charm_library set type = 'Universal' where ability = 'Embassy / Stealth' and name = 'Illimitable Master Fence';
update public.charm_library set type = 'Universal' where ability = 'Embassy / Integrity' and name = 'Motive-Discerning Technique';
update public.charm_library set type = 'Universal' where ability = 'Embassy' and name = 'The Perfect Bargain';
update public.charm_library set type = 'Universal' where ability = 'Embassy' and name = 'The Perfect Price';
update public.charm_library set type = 'Universal' where ability = 'Embassy / Presence' and name = 'Second Chance Approach';
update public.charm_library set type = 'Universal' where ability = 'Embassy' and name = 'Strange Tongue Understanding';
update public.charm_library set type = 'Universal' where ability = 'Integrity' and name = 'Guarded Mind Meditation';
update public.charm_library set type = 'Universal' where ability = 'Integrity' and name = 'Integrity-Protecting Principle';
update public.charm_library set type = 'Universal' where ability = 'Integrity' and name = 'Resolve Bolstering Declaration';
update public.charm_library set type = 'Universal' where ability = 'Integrity' and name = 'Righteous Lion Spirit';
update public.charm_library set type = 'Universal' where ability = 'Integrity' and name = 'Spirit-Maintaining Maneuver';
update public.charm_library set type = 'Universal' where ability = 'Integrity' and name = 'Stubborn Boar Defense';
update public.charm_library set type = 'Universal' where ability = 'Navigate' and name = 'As the Crow Flies';
update public.charm_library set type = 'Universal' where ability = 'Navigate' and name = 'Beast-Uplifting Harmony';
update public.charm_library set type = 'Universal' where ability = 'Navigate' and name = 'Calling the Rider''s Companion';
update public.charm_library set type = 'Universal' where ability = 'Navigate' and name = 'Fathoms-Fed Spirit';
update public.charm_library set type = 'Universal' where ability = 'Navigate / Physique' and name = 'Hardship-Surviving Spirit';
update public.charm_library set type = 'Universal' where ability = 'Navigate' and name = 'Hidden Shortcut Revelation';
update public.charm_library set type = 'Universal' where ability = 'Navigate' and name = 'Immortal Mariner''s Advantage';
update public.charm_library set type = 'Universal' where ability = 'Navigate' and name = 'Rider-and-Mount Unity';
update public.charm_library set type = 'Universal' where ability = 'Navigate' and name = 'Swift Artillery Technique';
update public.charm_library set type = 'Universal' where ability = 'Navigate' and name = 'Trackless Region Navigation';
update public.charm_library set type = 'Universal' where ability = 'Performance / Stealth' and name = 'Distracting Patter Technique';
update public.charm_library set type = 'Universal' where ability = 'Performance' and name = 'Flawless Brush Discipline';
update public.charm_library set type = 'Universal' where ability = 'Performance / Presence' and name = 'Greatness-Inspiring Aura';
update public.charm_library set type = 'Universal' where ability = 'Performance' and name = 'Masterful Performance Exercise';
update public.charm_library set type = 'Universal' where ability = 'Performance' and name = 'Memetic Dogma Discipline';
update public.charm_library set type = 'Universal' where ability = 'Performance' and name = 'Poetic Expression Style';
update public.charm_library set type = 'Universal' where ability = 'Performance / Sagacity' and name = 'Spirit-Manifesting Word';
update public.charm_library set type = 'Universal' where ability = 'Performance' and name = 'Soul-Stirring Cantata';
update public.charm_library set type = 'Universal' where ability = 'Performance' and name = 'Subtle Expression Method';
update public.charm_library set type = 'Universal' where ability = 'Physique (Might)' and name = 'Armored Scout''s Invigoration';
update public.charm_library set type = 'Universal' where ability = 'Physique (Might)' and name = 'Ten Ox Meditation';
update public.charm_library set type = 'Universal' where ability = 'Physique (Resistance)' and name = 'Body Mending Meditation';
update public.charm_library set type = 'Universal' where ability = 'Physique (Resistance) / Presence' and name = 'Captivating Battlefield Display';
update public.charm_library set type = 'Universal' where ability = 'Physique (Resistance)' and name = 'Iron Kettle Body';
update public.charm_library set type = 'Universal' where ability = 'Physique (Resistance)' and name = 'Malady-Resisting Meditation';
update public.charm_library set type = 'Universal' where ability = 'Physique (Resistance)' and name = 'Ox Body Technique';
update public.charm_library set type = 'Universal' where ability = 'Physique (Resistance)' and name = 'Power Gathering Temper';
update public.charm_library set type = 'Universal' where ability = 'Physique (Resistance)' and name = 'Spirit Strengthens the Skin';
update public.charm_library set type = 'Universal' where ability = 'Presence / War' and name = 'Battalion-Breaking Shout';
update public.charm_library set type = 'Universal' where ability = 'Presence' and name = 'Cat''s Puffed Tail';
update public.charm_library set type = 'Universal' where ability = 'Presence' and name = 'Dread Tiger''s Symmetry';
update public.charm_library set type = 'Universal' where ability = 'Presence' and name = 'Glorious Presence Technique';
update public.charm_library set type = 'Universal' where ability = 'Presence' and name = 'Harmonious Presence Meditation';
update public.charm_library set type = 'Universal' where ability = 'Presence' and name = 'Irresistible Presence Technique';
update public.charm_library set type = 'Universal' where ability = 'Presence' and name = 'Listener-Swaying Argument';
update public.charm_library set type = 'Universal' where ability = 'Presence / Stealth' and name = 'Suspicion-Allaying Gesture';
update public.charm_library set type = 'Universal' where ability = 'Presence / War' and name = 'Underling-Promoting Practice';
update public.charm_library set type = 'Universal' where ability = 'Presence / War' and name = 'Worshipful Lackey Acquisition';
update public.charm_library set type = 'Universal' where ability = 'Ranged Combat' and name = 'Arrow Storm Attack';
update public.charm_library set type = 'Universal' where ability = 'Ranged Combat' and name = 'Double Distance Technique';
update public.charm_library set type = 'Universal' where ability = 'Ranged Combat / Sagacity' and name = 'Glorious Exalted Bolt';
update public.charm_library set type = 'Universal' where ability = 'Ranged Combat' and name = 'No Arrow Wasted';
update public.charm_library set type = 'Universal' where ability = 'Ranged Combat' and name = 'Phantom Arrow';
update public.charm_library set type = 'Universal' where ability = 'Ranged Combat' and name = 'Reflex Shot Technique';
update public.charm_library set type = 'Universal' where ability = 'Ranged Combat' and name = 'Revolving Bow Discipline';
update public.charm_library set type = 'Universal' where ability = 'Ranged Combat' and name = 'Sharpshooter''s Clever Tricks';
update public.charm_library set type = 'Universal' where ability = 'Ranged Combat' and name = 'Streaming Arrow Stance';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Knowledge)' and name = 'Archive Mind Mentality';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Knowledge)' and name = 'Essence-Lending Method';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Knowledge)' and name = 'Harmonious Academic Methodology';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Knowledge)' and name = 'Necromantic Initiation';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Knowledge)' and name = 'Sorcerous Initiation';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Knowledge)' and name = 'Spirit-Repelling Diagram';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Knowledge)' and name = 'Spirit-Slaying Stance';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Knowledge)' and name = 'Swift-Hands Casting';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Knowledge)' and name = 'Truth-Rendering Gaze';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Knowledge)' and name = 'Will-Bolstering Method';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Medicine)' and name = 'Master Physician Technique';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Medicine)' and name = 'Flawless Diagnosis Technique';
update public.charm_library set type = 'Universal' where ability = 'Sagacity (Medicine)' and name = 'Wellness-Restoring Meditation';
update public.charm_library set type = 'Universal' where ability = 'Stealth' and name = 'A Drop Amongst the Ocean';
update public.charm_library set type = 'Universal' where ability = 'Stealth' and name = 'Doubt-Sealing Heist';
update public.charm_library set type = 'Universal' where ability = 'Stealth' and name = 'Evidence Placing Method';
update public.charm_library set type = 'Universal' where ability = 'Stealth' and name = 'Flawlessly Impenetrable Disguise';
update public.charm_library set type = 'Universal' where ability = 'Stealth' and name = 'Guiding Shadow Shroud';
update public.charm_library set type = 'Universal' where ability = 'Stealth' and name = 'Perfect Shadow Stillness';
update public.charm_library set type = 'Universal' where ability = 'Stealth' and name = 'Seasoned Criminal Method';
update public.charm_library set type = 'Universal' where ability = 'War' and name = 'Battle Plan Rumination';
update public.charm_library set type = 'Universal' where ability = 'War' and name = 'Cunning Warrior Regimen';
update public.charm_library set type = 'Universal' where ability = 'War' and name = 'Fearless Vanguard Technique';
update public.charm_library set type = 'Universal' where ability = 'War' and name = 'League of Iron Preparation';
update public.charm_library set type = 'Universal' where ability = 'War' and name = 'Mouse Conquers the Lion';
update public.charm_library set type = 'Universal' where ability = 'War' and name = 'Panic the Wounded Beast';
update public.charm_library set type = 'Universal' where ability = 'War' and name = 'Rally the Broken Company';
update public.charm_library set type = 'Abyssal' where ability = 'Athletics' and name = 'Death Approaches';
update public.charm_library set type = 'Abyssal' where ability = 'Athletics' and name = 'Ebon Lightning Flash';
update public.charm_library set type = 'Abyssal' where ability = 'Awareness' and name = 'Corpse Questioning Technique';
update public.charm_library set type = 'Abyssal' where ability = 'Awareness' and name = 'Wickedness-Unveiling Method';
update public.charm_library set type = 'Abyssal' where ability = 'Awareness' and name = 'Ghostly Sentinel Technique';
update public.charm_library set type = 'Abyssal' where ability = 'Close Combat' and name = 'Artful Maiming Onslaught';
update public.charm_library set type = 'Abyssal' where ability = 'Close Combat' and name = 'Iron Maiden''s Kiss';
update public.charm_library set type = 'Abyssal' where ability = 'Close Combat' and name = 'Soul-Drinking Bite';
update public.charm_library set type = 'Abyssal' where ability = 'Close Combat' and name = 'Void Avatar Embodiment';
update public.charm_library set type = 'Abyssal' where ability = 'Craft' and name = 'All-Consuming Entropy Attack';
update public.charm_library set type = 'Abyssal' where ability = 'Craft' and name = 'Haunting Monumental Artifice';
update public.charm_library set type = 'Abyssal' where ability = 'Embassy / Presence' and name = 'Ghost-Emperor Edict';
update public.charm_library set type = 'Abyssal' where ability = 'Embassy / Presence' and name = 'Killing Words Technique';
update public.charm_library set type = 'Abyssal' where ability = 'Embassy / Presence' and name = 'Reverent Mortuary Witness';
update public.charm_library set type = 'Abyssal' where ability = 'Integrity' and name = 'Murder-Saint Dedication';
update public.charm_library set type = 'Abyssal' where ability = 'Navigate' and name = 'Stepping Outside Existence';
update public.charm_library set type = 'Abyssal' where ability = 'Navigate' and name = 'Unhallowed Ghost Ship';
update public.charm_library set type = 'Abyssal' where ability = 'Performance' and name = 'Elegy for the Fallen';
update public.charm_library set type = 'Abyssal' where ability = 'Performance' and name = 'Withering Dirge';
update public.charm_library set type = 'Abyssal' where ability = 'Physique' and name = 'Death Needs Nothing';
update public.charm_library set type = 'Abyssal' where ability = 'Physique' and name = 'Cadaverous Torpor Technique';
update public.charm_library set type = 'Abyssal' where ability = 'Presence' and name = 'Corpse-Commanding Attitude';
update public.charm_library set type = 'Abyssal' where ability = 'Presence' and name = 'Death-Pact Ascension';
update public.charm_library set type = 'Abyssal' where ability = 'Ranged Combat' and name = 'First Blood Impulse';
update public.charm_library set type = 'Abyssal' where ability = 'Ranged Combat' and name = 'Hundred Paces Bite';
update public.charm_library set type = 'Abyssal' where ability = 'Sagacity / War' and name = 'Life-Mocking Assembly';
update public.charm_library set type = 'Abyssal' where ability = 'Sagacity' and name = 'Pestilence-Bearing Touch';
update public.charm_library set type = 'Abyssal' where ability = 'Stealth' and name = 'Stifled Cry Exercise';
update public.charm_library set type = 'Abyssal' where ability = 'Stealth' and name = 'Shadow Cloak Technique';
update public.charm_library set type = 'Abyssal' where ability = 'War' and name = 'Arise and Slaughter';
update public.charm_library set type = 'Abyssal' where ability = 'War' and name = 'Shadowed Warfare Methodology';
update public.charm_library set type = 'Alchemical' where ability = 'Finesse' and name = 'Artificer''s Keen Eye';
update public.charm_library set type = 'Alchemical' where ability = 'General' and name = 'Augmented Attribute';
update public.charm_library set type = 'Alchemical' where ability = 'General' and name = 'Portable Utility Compartment';
update public.charm_library set type = 'Alchemical' where ability = 'Finesse' and name = 'Battle Form Mimicry';
update public.charm_library set type = 'Alchemical' where ability = 'Finesse' and name = 'Better Than New';
update public.charm_library set type = 'Alchemical' where ability = 'Finesse' and name = 'Bone-and-Steel Destruction';
update public.charm_library set type = 'Alchemical' where ability = 'Finesse' and name = 'Contingency Preparation Axiom';
update public.charm_library set type = 'Alchemical' where ability = 'Finesse' and name = 'Effective Leadership Algorithm';
update public.charm_library set type = 'Alchemical' where ability = 'Finesse' and name = 'Efficient Planning Matrix';
update public.charm_library set type = 'Alchemical' where ability = 'Finesse' and name = 'Fine-Tuning';
update public.charm_library set type = 'Alchemical' where ability = 'Finesse' and name = 'Phase Shifting Apparatus';
update public.charm_library set type = 'Alchemical' where ability = 'Finesse' and name = 'Subtle Concept Introduction Method';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Advisor''s Sage Instruction';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Celestial Overseer Concordat';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Exhaustive Interrogation Method';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Future-Proclaiming Canticle';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Insightful Managerial Aptitude';
update public.charm_library set type = 'Alchemical' where ability = 'Force / Fortitude' and name = 'Lifesign Detecting Scan';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Machine-God Protector Mode';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Morale Building Declaration';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Omnipresent Guardian Directive';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Perfected Union Patterning';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Priority-Discerning Protocol';
update public.charm_library set type = 'Alchemical' where ability = 'Force / Fortitude' and name = 'Relentless Tracking Protocol';
update public.charm_library set type = 'Alchemical' where ability = 'Force' and name = 'Truth-and-Lies Detection';
update public.charm_library set type = 'Alchemical' where ability = 'Fortitude' and name = 'Body Reweaving Matrix';
update public.charm_library set type = 'Alchemical' where ability = 'Fortitude' and name = 'Identity Obfuscation Matrix';
update public.charm_library set type = 'Alchemical' where ability = 'Fortitude' and name = 'Material Resistance Procedure';
update public.charm_library set type = 'Alchemical' where ability = 'Fortitude' and name = 'Outlier Analysis Method';
update public.charm_library set type = 'Alchemical' where ability = 'Fortitude' and name = 'Optical Shroud';
update public.charm_library set type = 'Alchemical' where ability = 'Fortitude' and name = 'Reinforced Chassis';
update public.charm_library set type = 'Alchemical' where ability = 'Fortitude' and name = 'Terraforming Protocol';
update public.charm_library set type = 'Alchemical' where ability = 'Fortitude' and name = 'Verbatim Recall';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Athletics' and name = 'Dragon Surmounts the Waterfall';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Athletics' and name = 'Safety Among Enemies';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Awareness' and name = 'All-Encompassing Earth Sense';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Awareness / Sagacity' and name = 'Fivefold Resonance Sense';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Awareness' and name = 'Sense-Riding Technique';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Close Combat' and name = 'Current Sweeps to Sea';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Close Combat' and name = 'Dragon-Graced Weapon';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Close Combat' and name = 'Drowning Embrace';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Close Combat' and name = 'Root-and-Hand Merging';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Craft / War' and name = 'Flaw-Finding Examination';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Craft / Performance' and name = 'Passion-Inflaming Artistry';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Craft' and name = 'Stones-from-Rubble Restoration';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Embassy' and name = 'Thoughtful Gift Technique';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Embassy / Performance' and name = 'Wind-Carried-Words Technique';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Embassy / War' and name = 'With One Mind';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Integrity' and name = 'Granite Curtain of Serenity';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Integrity' and name = 'Oath of the Ten Thousand Dragons';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Integrity' and name = 'Unflagging Vengeance Meditation';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Navigate' and name = 'Benediction of the Living Ship';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Navigate' and name = 'Blazing Charger Attack';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Physique' and name = 'Elemental Protection Technique';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Presence' and name = 'Entombed Mind Technique';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Ranged Combat' and name = 'Arbor Sentinel Technique';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Ranged Combat / Sagacity' and name = 'Elemental Burst Technique';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Sagacity / War' and name = 'Dragon Vortex Attack';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Stealth' and name = 'Flowing God-Dragon Stance';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'Stealth' and name = 'Rose-Among-Thorns Distinction';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'War' and name = 'Storm-Calling Strategies';
update public.charm_library set type = 'Dragon-Blooded' where ability = 'War' and name = 'Ramparts of Obedient Earth';
update public.charm_library set type = 'Getimian' where ability = 'General' and name = 'Alchemic Power Reserve';
update public.charm_library set type = 'Getimian' where ability = 'General' and name = 'Fate-Unwinding Denial';
update public.charm_library set type = 'Getimian' where ability = 'General' and name = 'Space-and-Time Understanding';
update public.charm_library set type = 'Getimian' where ability = 'General' and name = 'Summoned from Time';
update public.charm_library set type = 'Getimian' where ability = 'Finesse' and name = 'Bent Reality Stance';
update public.charm_library set type = 'Getimian' where ability = 'Finesse' and name = 'Devil-Queen''s Court';
update public.charm_library set type = 'Getimian' where ability = 'Finesse' and name = 'Distilled-Emotion Elixir';
update public.charm_library set type = 'Getimian' where ability = 'Finesse' and name = 'Here-and-Everywhere Approach';
update public.charm_library set type = 'Getimian' where ability = 'Finesse' and name = 'Forgetting the Lie';
update public.charm_library set type = 'Getimian' where ability = 'Finesse' and name = 'Sleeper-Guiding Whisper';
update public.charm_library set type = 'Getimian' where ability = 'Finesse' and name = 'Unavoidable Confrontation';
update public.charm_library set type = 'Getimian' where ability = 'Force' and name = 'Culture-Hero Usurpation';
update public.charm_library set type = 'Getimian' where ability = 'Force' and name = 'Finding the Chorus';
update public.charm_library set type = 'Getimian' where ability = 'Force' and name = 'Icon-Obliterating Passion';
update public.charm_library set type = 'Getimian' where ability = 'Force' and name = 'Ideology Redefinition Trick';
update public.charm_library set type = 'Getimian' where ability = 'Force' and name = 'Perspective-Consuming Grandeur';
update public.charm_library set type = 'Getimian' where ability = 'Force' and name = 'Reality Embellishment Approach';
update public.charm_library set type = 'Getimian' where ability = 'Force' and name = 'The Filial Chain';
update public.charm_library set type = 'Getimian' where ability = 'Force' and name = 'Throne-Smashing Ambition';
update public.charm_library set type = 'Getimian' where ability = 'Force' and name = 'Wall-Denying Fury';
update public.charm_library set type = 'Getimian' where ability = 'Fortitude' and name = 'Constant Problem Tactic';
update public.charm_library set type = 'Getimian' where ability = 'Fortitude' and name = 'Courage-Decanting Alchemy';
update public.charm_library set type = 'Getimian' where ability = 'Fortitude' and name = 'Folding Space';
update public.charm_library set type = 'Getimian' where ability = 'Fortitude' and name = 'One-on-One Imprisonment';
update public.charm_library set type = 'Getimian' where ability = 'Fortitude' and name = 'Spatial Disjunction';
update public.charm_library set type = 'Getimian' where ability = 'Fortitude' and name = 'Truth is Relative';
update public.charm_library set type = 'Getimian' where ability = 'Fortitude' and name = 'Unforged Masterworks';
update public.charm_library set type = 'Infernal' where ability = 'General' and name = 'Devil-Body Incarnation';
update public.charm_library set type = 'Infernal' where ability = 'Athletics' and name = 'Joy in Violence';
update public.charm_library set type = 'Infernal' where ability = 'Athletics' and name = 'Skin-Flaying Wind Dance';
update public.charm_library set type = 'Infernal' where ability = 'Awareness' and name = 'Naked Soul Insight';
update public.charm_library set type = 'Infernal' where ability = 'Awareness' and name = 'Witness to Darkness';
update public.charm_library set type = 'Infernal' where ability = 'Close Combat' and name = 'Death of All Happiness';
update public.charm_library set type = 'Infernal' where ability = 'Close Combat' and name = 'Hideous Hundred-Limb Strike';
update public.charm_library set type = 'Infernal' where ability = 'Close Combat' and name = 'Wrath-Stoked Onslaught';
update public.charm_library set type = 'Infernal' where ability = 'Craft' and name = 'Claiming the Devil''s Due';
update public.charm_library set type = 'Infernal' where ability = 'Embassy' and name = 'Golden Years Tarnished Black';
update public.charm_library set type = 'Infernal' where ability = 'Embassy' and name = 'Naked Soul Insight';
update public.charm_library set type = 'Infernal' where ability = 'Embassy' and name = 'Our Little Secret';
update public.charm_library set type = 'Infernal' where ability = 'Embassy' and name = 'Unbreakable Laws of Hell';
update public.charm_library set type = 'Infernal' where ability = 'Integrity' and name = 'Acquainted with Deception';
update public.charm_library set type = 'Infernal' where ability = 'Integrity' and name = 'Body Obeys Ego';
update public.charm_library set type = 'Infernal' where ability = 'Integrity' and name = 'Broken Silence Laughter Defense';
update public.charm_library set type = 'Infernal' where ability = 'Integrity' and name = 'Cosmic Transcendence of (Virtue)';
update public.charm_library set type = 'Infernal' where ability = 'Integrity' and name = 'Endless Nightmare Vigilance';
update public.charm_library set type = 'Infernal' where ability = 'Integrity' and name = 'Inevitable Betrayal Insight';
update public.charm_library set type = 'Infernal' where ability = 'Integrity' and name = 'Intolerable Burning Truths';
update public.charm_library set type = 'Infernal' where ability = 'Integrity' and name = 'Will-Crushing Force';
update public.charm_library set type = 'Infernal' where ability = 'Navigate' and name = 'Desert-and-Flame Endurance';
update public.charm_library set type = 'Infernal' where ability = 'Navigate' and name = 'Oasis-Scouring Malediction';
update public.charm_library set type = 'Infernal' where ability = 'Navigate' and name = 'Taste-of-Hell Infliction';
update public.charm_library set type = 'Infernal' where ability = 'Performance' and name = 'Devil Emperor Edict';
update public.charm_library set type = 'Infernal' where ability = 'Performance' and name = 'Symphony of Sinful Prayers';
update public.charm_library set type = 'Infernal' where ability = 'Performance' and name = 'Wish-Granting Wickedness';
update public.charm_library set type = 'Infernal' where ability = 'Physique' and name = 'Ceaseless Demon Hunger';
update public.charm_library set type = 'Infernal' where ability = 'Physique' and name = 'Scars Become Armor';
update public.charm_library set type = 'Infernal' where ability = 'Physique' and name = 'Venom Blood Revenge';
update public.charm_library set type = 'Infernal' where ability = 'Physique' and name = 'Viridian Rust Defense';
update public.charm_library set type = 'Infernal' where ability = 'Ranged Combat' and name = 'Blinded by Hellfire';
update public.charm_library set type = 'Infernal' where ability = 'Sagacity' and name = 'Constructive Convergence of Principles';
update public.charm_library set type = 'Infernal' where ability = 'Sagacity' and name = 'Dark Miracle Mimicry';
update public.charm_library set type = 'Infernal' where ability = 'Sagacity' and name = 'Inner Devil Unchained';
update public.charm_library set type = 'Infernal' where ability = 'Sagacity' and name = 'Mind-Hand Manipulation';
update public.charm_library set type = 'Infernal' where ability = 'Sagacity' and name = 'Shadow Spite Curse';
update public.charm_library set type = 'Infernal' where ability = 'Sagacity' and name = 'Skin-Twisting Metamorphosis';
update public.charm_library set type = 'Infernal' where ability = 'Stealth' and name = 'Nemesis Self Imagined Anew';
update public.charm_library set type = 'Infernal' where ability = 'War' and name = 'Every Man a Devil';
update public.charm_library set type = 'Liminal' where ability = 'General' and name = 'Corporeal Reformation';
update public.charm_library set type = 'Liminal' where ability = 'General' and name = 'Gravedigger''s Elan';
update public.charm_library set type = 'Liminal' where ability = 'General' and name = 'Last Exhalation of Secrets';
update public.charm_library set type = 'Liminal' where ability = 'General' and name = 'Life, Death, and Rebirth';
update public.charm_library set type = 'Liminal' where ability = 'General' and name = 'Scent of Blood';
update public.charm_library set type = 'Liminal' where ability = 'General' and name = 'Towering Corporeal Pillar';
update public.charm_library set type = 'Liminal' where ability = 'General' and name = 'True Undeath';
update public.charm_library set type = 'Liminal' where ability = 'General' and name = 'Undying Body';
update public.charm_library set type = 'Liminal' where ability = 'Finesse' and name = 'Black Wind of Desire';
update public.charm_library set type = 'Liminal' where ability = 'Finesse' and name = 'Bone Deep Body Reconfiguration';
update public.charm_library set type = 'Liminal' where ability = 'Finesse' and name = 'Death-Sensing Probe';
update public.charm_library set type = 'Liminal' where ability = 'Finesse' and name = 'Honored Memories of Mastery';
update public.charm_library set type = 'Liminal' where ability = 'Finesse' and name = 'Soft Touch of Hospice';
update public.charm_library set type = 'Liminal' where ability = 'Finesse' and name = 'Tomb and Ruin Inspection';
update public.charm_library set type = 'Liminal' where ability = 'Finesse' and name = 'Web of Veins';
update public.charm_library set type = 'Liminal' where ability = 'Finesse' and name = 'Weeping Crimson Gaze';
update public.charm_library set type = 'Liminal' where ability = 'Force' and name = 'Autopsy-and-Dissection Glance';
update public.charm_library set type = 'Liminal' where ability = 'Force' and name = 'Bloodslick Crimson Barb';
update public.charm_library set type = 'Liminal' where ability = 'Force' and name = 'Deathbound Mania';
update public.charm_library set type = 'Liminal' where ability = 'Force' and name = 'Embodied Resonance Transplant';
update public.charm_library set type = 'Liminal' where ability = 'Force' and name = 'Ever-Steady Graveward Heart';
update public.charm_library set type = 'Liminal' where ability = 'Force' and name = 'Muscle-Hemorrhaging Exertion';
update public.charm_library set type = 'Liminal' where ability = 'Force' and name = 'Unliving Industry';
update public.charm_library set type = 'Liminal' where ability = 'Fortitude' and name = 'Blossoming Clot Ministrations';
update public.charm_library set type = 'Liminal' where ability = 'Fortitude' and name = 'Breath-Tasting Ward';
update public.charm_library set type = 'Liminal' where ability = 'Fortitude' and name = 'Cyclic Scythe';
update public.charm_library set type = 'Liminal' where ability = 'Fortitude' and name = 'Investiture of Flesh';
update public.charm_library set type = 'Liminal' where ability = 'Fortitude' and name = 'Life-Scaffolding Survival';
update public.charm_library set type = 'Liminal' where ability = 'Fortitude' and name = 'Pain Syphoning Sigh';
update public.charm_library set type = 'Liminal' where ability = 'Fortitude' and name = 'Unleash Homunculus';
update public.charm_library set type = 'Lunar' where ability = 'Shapeshifting' and name = 'Ant-and-Yeddim Wisdom';
update public.charm_library set type = 'Lunar' where ability = 'Shapeshifting' and name = 'Chimera-Soul Expression';
update public.charm_library set type = 'Lunar' where ability = 'Shapeshifting' and name = 'Changing Phases Transformation';
update public.charm_library set type = 'Lunar' where ability = 'Shapeshifting' and name = 'Hybrid Body Transformation';
update public.charm_library set type = 'Lunar' where ability = 'Shapeshifting' and name = 'Many-Faced Moon Transformation';
update public.charm_library set type = 'Lunar' where ability = 'Shapeshifting' and name = 'Manifold Hunter''s Tactics';
update public.charm_library set type = 'Lunar' where ability = 'Shapeshifting' and name = 'Mountainous Spirit Expression';
update public.charm_library set type = 'Lunar' where ability = 'Finesse' and name = 'Cunning Anglerfish Decoy';
update public.charm_library set type = 'Lunar' where ability = 'Finesse' and name = 'Hungry All-Consuming Cloud';
update public.charm_library set type = 'Lunar' where ability = 'Finesse' and name = 'Hunter-Baffling Quarry''s Curse';
update public.charm_library set type = 'Lunar' where ability = 'Finesse' and name = 'Laughing Devil Distraction';
update public.charm_library set type = 'Lunar' where ability = 'Finesse' and name = 'Living Hive Transformation';
update public.charm_library set type = 'Lunar' where ability = 'Finesse' and name = 'Predator-and-Prey Mirror';
update public.charm_library set type = 'Lunar' where ability = 'Finesse' and name = 'Quicksilver Second Face';
update public.charm_library set type = 'Lunar' where ability = 'Finesse' and name = 'Shadow Talon Execution';
update public.charm_library set type = 'Lunar' where ability = 'Force' and name = 'Beast-Soul Awakening';
update public.charm_library set type = 'Lunar' where ability = 'Force' and name = 'Boundary-Marking Meditation';
update public.charm_library set type = 'Lunar' where ability = 'Force' and name = 'Butterfly Eyes Mirage';
update public.charm_library set type = 'Lunar' where ability = 'Force' and name = 'Grasping Pseudopod Method';
update public.charm_library set type = 'Lunar' where ability = 'Force' and name = 'Insidious Lunar Transformation';
update public.charm_library set type = 'Lunar' where ability = 'Force' and name = 'Kraken-Arm Lash';
update public.charm_library set type = 'Lunar' where ability = 'Force' and name = 'Memory-Drinking Meditation';
update public.charm_library set type = 'Lunar' where ability = 'Force' and name = 'Nightmare Scar Memento';
update public.charm_library set type = 'Lunar' where ability = 'Force' and name = 'Sharing Luna''s Gifts';
update public.charm_library set type = 'Lunar' where ability = 'Fortitude' and name = 'Adder Fang Method';
update public.charm_library set type = 'Lunar' where ability = 'Fortitude' and name = 'Dauntless Yeddim Caravan';
update public.charm_library set type = 'Lunar' where ability = 'Fortitude' and name = 'Creation Spanning Passion';
update public.charm_library set type = 'Lunar' where ability = 'Fortitude' and name = 'Relentless Lunar Fury';
update public.charm_library set type = 'Lunar' where ability = 'Fortitude' and name = 'Shattered Yoke Fury';
update public.charm_library set type = 'Lunar' where ability = 'Fortitude' and name = 'Spider-Amid-Roses Discernment';
update public.charm_library set type = 'Sidereal' where ability = 'Athletics' and name = 'Avoidance';
update public.charm_library set type = 'Sidereal' where ability = 'Athletics' and name = 'Invisible Motion';
update public.charm_library set type = 'Sidereal' where ability = 'Awareness' and name = 'Efficient Secretary Technique';
update public.charm_library set type = 'Sidereal' where ability = 'Awareness' and name = 'Last Vision';
update public.charm_library set type = 'Sidereal' where ability = 'Awareness' and name = 'Of Truths Best Unspoken';
update public.charm_library set type = 'Sidereal' where ability = 'Close Combat' and name = 'Heartless Maiden Trance';
update public.charm_library set type = 'Sidereal' where ability = 'Craft' and name = 'Mending Warped Designs';
update public.charm_library set type = 'Sidereal' where ability = 'Embassy' and name = 'Cash and Murder Games';
update public.charm_library set type = 'Sidereal' where ability = 'Embassy' and name = 'End Debate';
update public.charm_library set type = 'Sidereal' where ability = 'Embassy' and name = 'Icy Hand';
update public.charm_library set type = 'Sidereal' where ability = 'Embassy' and name = 'Lover''s Oath';
update public.charm_library set type = 'Sidereal' where ability = 'Embassy' and name = 'Willing Assumption of Chains';
update public.charm_library set type = 'Sidereal' where ability = 'Integrity' and name = 'Deferred Wounds';
update public.charm_library set type = 'Sidereal' where ability = 'Integrity' and name = 'Force Decision';
update public.charm_library set type = 'Sidereal' where ability = 'Integrity' and name = 'Unavoidable Sorrow';
update public.charm_library set type = 'Sidereal' where ability = 'Navigate' and name = 'Fortuitous Wandering';
update public.charm_library set type = 'Sidereal' where ability = 'Navigate' and name = 'In the Nick of Time';
update public.charm_library set type = 'Sidereal' where ability = 'Navigate' and name = 'Ordained Bridle of Mercury';
update public.charm_library set type = 'Sidereal' where ability = 'Navigate' and name = 'Wilderness-Commanding Practice';
update public.charm_library set type = 'Sidereal' where ability = 'Performance' and name = 'Abandoned Words Curse';
update public.charm_library set type = 'Sidereal' where ability = 'Performance' and name = 'Defense of Shining Joy';
update public.charm_library set type = 'Sidereal' where ability = 'Performance' and name = 'Faultless Ceremony';
update public.charm_library set type = 'Sidereal' where ability = 'Physique' and name = 'Shield of Mars';
update public.charm_library set type = 'Sidereal' where ability = 'Physique' and name = 'Unswerving Juggernaut Principle';
update public.charm_library set type = 'Sidereal' where ability = 'Presence' and name = 'Shun the Smiling Lady';
update public.charm_library set type = 'Sidereal' where ability = 'Presence' and name = 'Under the Crimson Banner';
update public.charm_library set type = 'Sidereal' where ability = 'Ranged Combat' and name = 'Shadow-Piercing Needle';
update public.charm_library set type = 'Sidereal' where ability = 'Ranged Combat' and name = 'Transcendent Hatchet of Fate';
update public.charm_library set type = 'Sidereal' where ability = 'Sagacity' and name = 'Thought-Swiping Distraction';
update public.charm_library set type = 'Sidereal' where ability = 'Stealth' and name = 'Name-Pilfering Practice';
update public.charm_library set type = 'Sidereal' where ability = 'Stealth' and name = 'Walking Outside Fate';
update public.charm_library set type = 'Solar' where ability = 'Athletics' and name = 'Unfettered Sun Evasion';
update public.charm_library set type = 'Solar' where ability = 'Awareness' and name = 'Meditation on Rivalry';
update public.charm_library set type = 'Solar' where ability = 'Awareness' and name = 'Unconquered Sun''s Sight';
update public.charm_library set type = 'Solar' where ability = 'Close Combat' and name = 'Behemoth-Slaying Attitude';
update public.charm_library set type = 'Solar' where ability = 'Close Combat' and name = 'Glorious Solar Arsenal';
update public.charm_library set type = 'Solar' where ability = 'Close Combat' and name = 'Orichalcum Battle Soul';
update public.charm_library set type = 'Solar' where ability = 'Close Combat' and name = 'Star-Cleaving Crater';
update public.charm_library set type = 'Solar' where ability = 'Craft' and name = 'Joyous Handiwork Genius';
update public.charm_library set type = 'Solar' where ability = 'Craft' and name = 'Technique-from-Taste Approach';
update public.charm_library set type = 'Solar' where ability = 'Embassy' and name = 'Vacant Station Scheme';
update public.charm_library set type = 'Solar' where ability = 'Integrity' and name = 'Aspect of the Virtuous Warrior';
update public.charm_library set type = 'Solar' where ability = 'Integrity' and name = 'Principle-Maintaining Method';
update public.charm_library set type = 'Solar' where ability = 'Integrity' and name = 'Sun King Radiance';
update public.charm_library set type = 'Solar' where ability = 'Navigate' and name = 'God-Bearing Juggernaut';
update public.charm_library set type = 'Solar' where ability = 'Navigate' and name = 'Ship-Claiming Stance';
update public.charm_library set type = 'Solar' where ability = 'Navigate' and name = 'Waves-and-Rivers Ranging';
update public.charm_library set type = 'Solar' where ability = 'Performance' and name = 'Phantom-Conjuring Performance';
update public.charm_library set type = 'Solar' where ability = 'Performance' and name = 'Rocks and Storms Chorus';
update public.charm_library set type = 'Solar' where ability = 'Performance' and name = 'Virtue-Shaping Harmony';
update public.charm_library set type = 'Solar' where ability = 'Physique' and name = 'Endurance of a Thousand Cuts';
update public.charm_library set type = 'Solar' where ability = 'Presence' and name = 'Dissident-Searing Intent';
update public.charm_library set type = 'Solar' where ability = 'Presence' and name = 'Hypnotic Tongue Technique';
update public.charm_library set type = 'Solar' where ability = 'Ranged Combat' and name = 'Dazzling Flare';
update public.charm_library set type = 'Solar' where ability = 'Ranged Combat' and name = 'Observer-Deceiving Attack';
update public.charm_library set type = 'Solar' where ability = 'Sagacity' and name = 'Healer''s Boundless Grace';
update public.charm_library set type = 'Solar' where ability = 'Sagacity' and name = 'Wyld-Shaping Technique';
update public.charm_library set type = 'Solar' where ability = 'Stealth' and name = 'King of Thieves Spirit';
update public.charm_library set type = 'Solar' where ability = 'Stealth' and name = 'Shroud of Night''s Law';
update public.charm_library set type = 'Solar' where ability = 'War' and name = 'General of the All-Seeing Sun';
update public.charm_library set type = 'Solar' where ability = 'War' and name = 'Solar Tactician''s Acumen';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Athletics' and name = 'Deep-Rooted Tenacity';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Athletics' and name = 'Seven League Stride';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Awareness' and name = 'Bone-Setter''s Discernment';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Awareness' and name = 'Creation-Embracing Gaze';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Awareness' and name = 'Stalks Have Eyes';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Awareness' and name = 'Taste of Familiar Earth';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Awareness' and name = 'Strawmaiden''s Calling';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Craft' and name = 'Prodigious Bounty';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Craft' and name = 'Stout-Hearted Brewing Style';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Craft' and name = 'Watering Parched Fields';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Embassy' and name = 'Sister to Aurochs';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Physique' and name = 'Belle of the Bee';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Physique' and name = 'Fieldhand Hefts the Haywain';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Physique' and name = 'Giant-Toppling Spirit';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Physique' and name = 'Millstone Meteor Technique';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Physique' and name = 'No Time for Idle Dreaming';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Physique' and name = 'Rough-Spun Hero Raiment';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Physique' and name = 'Stalk Blunts the Sickle';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Physique' and name = 'Towering Redwood Stature';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Performance' and name = 'Caller of Wind and Rain';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Presence' and name = 'Fieldhand Clarion';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Presence' and name = 'Simple and Resounding Honesty';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Presence' and name = 'Sweat and Toil Radiance';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Presence' and name = 'This Far and No Further';
update public.charm_library set type = 'Strawmaiden Janest' where ability = 'Presence' and name = 'Vermin Clearing Shout';
update public.charm_library set type = 'Martial Arts' where ability = 'Crane Style' and name = 'Empowering Justice Redirection';
update public.charm_library set type = 'Martial Arts' where ability = 'Crane Style' and name = 'Fluttering Cry of Warning';
update public.charm_library set type = 'Martial Arts' where ability = 'Crane Style' and name = 'Crane Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Crane Style' and name = 'Humbling Enlightenment Commentary';
update public.charm_library set type = 'Martial Arts' where ability = 'Ebon Shadow Style' and name = 'Nothing but Shadows';
update public.charm_library set type = 'Martial Arts' where ability = 'Ebon Shadow Style' and name = 'Ebon Shadow Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Ebon Shadow Style' and name = 'Throat-Slitting Shadow Strike';
update public.charm_library set type = 'Martial Arts' where ability = 'Mantis Style' and name = 'Iron-Arm Block';
update public.charm_library set type = 'Martial Arts' where ability = 'Mantis Style' and name = 'Crushing Claw Technique';
update public.charm_library set type = 'Martial Arts' where ability = 'Mantis Style' and name = 'Mantis Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Mantis Style' and name = 'Unfolding Retribution Strike';
update public.charm_library set type = 'Martial Arts' where ability = 'Righteous Devil Style' and name = 'Blossom of Inevitable Demise';
update public.charm_library set type = 'Martial Arts' where ability = 'Righteous Devil Style' and name = 'Righteous Devil Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Righteous Devil Style' and name = 'Burning Judgment Halo';
update public.charm_library set type = 'Martial Arts' where ability = 'Righteous Devil Style' and name = 'Caress of 1,000 Hells';
update public.charm_library set type = 'Martial Arts' where ability = 'Snake Style' and name = 'Serpentine Evasion';
update public.charm_library set type = 'Martial Arts' where ability = 'Snake Style' and name = 'Snake Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Snake Style' and name = 'Uncoiling Serpent Aura';
update public.charm_library set type = 'Martial Arts' where ability = 'Tiger Style' and name = 'Crimson Leaping Cat Technique';
update public.charm_library set type = 'Martial Arts' where ability = 'Tiger Style' and name = 'Tiger Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Tiger Style' and name = 'Angry Predator Frenzy';
update public.charm_library set type = 'Martial Arts' where ability = 'White Reaper Style' and name = 'White Reaper Form';
update public.charm_library set type = 'Martial Arts' where ability = 'White Reaper Style' and name = 'Bleeding Crescent Strike';
update public.charm_library set type = 'Martial Arts' where ability = 'White Reaper Style' and name = 'Flickering Corona Barrier';
update public.charm_library set type = 'Martial Arts' where ability = 'White Reaper Style' and name = 'Snow Follows Winter';
update public.charm_library set type = 'Martial Arts' where ability = 'Air Dragon Style' and name = 'Cloud-Treading Method';
update public.charm_library set type = 'Martial Arts' where ability = 'Air Dragon Style' and name = 'Air Dragon Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Air Dragon Style' and name = 'Lightning Strike Style';
update public.charm_library set type = 'Martial Arts' where ability = 'Air Dragon Style' and name = 'Wrathful Winds Roar';
update public.charm_library set type = 'Martial Arts' where ability = 'Earth Dragon Style' and name = 'Stillness-of-Stone Strike';
update public.charm_library set type = 'Martial Arts' where ability = 'Earth Dragon Style' and name = 'Earth Dragon Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Earth Dragon Style' and name = 'Hungry Earth Strike';
update public.charm_library set type = 'Martial Arts' where ability = 'Earth Dragon Style' and name = 'Shattering Fist Strike';
update public.charm_library set type = 'Martial Arts' where ability = 'Fire Dragon Style' and name = 'Searing Edge Attack';
update public.charm_library set type = 'Martial Arts' where ability = 'Fire Dragon Style' and name = 'Fire Dragon Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Fire Dragon Style' and name = 'Fiery Blade Attack';
update public.charm_library set type = 'Martial Arts' where ability = 'Fire Dragon Style' and name = 'Overwhelming Fire Majesty Stance';
update public.charm_library set type = 'Martial Arts' where ability = 'Water Dragon Style' and name = 'Drowning-in-Blood Technique';
update public.charm_library set type = 'Martial Arts' where ability = 'Water Dragon Style' and name = 'Flowing Water Defense';
update public.charm_library set type = 'Martial Arts' where ability = 'Water Dragon Style' and name = 'Water Dragon Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Water Dragon Style' and name = 'Foe-Restraining Whirlpool';
update public.charm_library set type = 'Martial Arts' where ability = 'Wood Dragon Style' and name = 'Soul-Marking Strike';
update public.charm_library set type = 'Martial Arts' where ability = 'Wood Dragon Style' and name = 'Wood Dragon Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Wood Dragon Style' and name = 'Unbreakable Fascination Exercise';
update public.charm_library set type = 'Martial Arts' where ability = 'Wood Dragon Style' and name = 'Soul Mastery';
update public.charm_library set type = 'Martial Arts' where ability = 'Prismatic Arrangement of Creation Style' and name = 'Four Magical Materials Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Prismatic Arrangement of Creation Style' and name = 'Soul Fire Shaper Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Prismatic Arrangement of Creation Style' and name = 'Games of Divinity Form';
update public.charm_library set type = 'Martial Arts' where ability = 'Prismatic Arrangement of Creation Style' and name = 'Prismatic Arrangement of Creation Form';
